#=====================================================================================
# Description: Pack OpenWrt for N1/Amlogic
# 
#=====================================================================================


name: Pack OpenWRT for N1/Amlogic

on:
  repository_dispatch:
    types: [Source_Code_Update_ophub, Package_Luci_Update]
  workflow_dispatch:
    inputs:
      openwrt_board:
        description: "Select Amlogic SoC"
        required: false
        default: "s905d"
        type: choice
        options:
          - all
          - s905x3_s905d_s912
          - a311d
          - s922x
          - s922x-n2
          - s922x-reva
          - s905x3
          - s905x2
          - s905x2-km3
          - s912
          - s912-m8s
          - s905d
          - s905d-ki
          - s905x
          - s905w
          - s905
          - s905l3a
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "5.15.84_6.1.1"
        type: choice
        options:
          - 5.4.228
          - 5.10.160
          - 5.15.84
          - 6.1.1
          - 5.4.228_5.10.160
          - 5.15.84_6.1.1
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean
      openwrt_size:
        description: "Set the rootfs size(Unit: MiB)."
        required: false
        default: "960"
    
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 420 # Add Time
#     if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Package Armvirt as OpenWrt(auto triggered)
      if: (!cancelled() && ${{github.event.event_type}} == "Source_Code_Update_ophub")
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: https://github.com/xlighting2017/Actions-Openwrt/releases/download/Immortalwrt_Armvirt/immortalwrt-armvirt-64-default-rootfs.tar.gz
        openwrt_board: "s905d"
        openwrt_kernel: "5.15.84_6.1.1"
        auto_kernel: true
        openwrt_size: "960"
        gh_token: ${{ secrets.GH_TOKEN }}
    
    - name: Package Armvirt as OpenWrt(with input)
      if: (!cancelled() && ${{ github.event.inputs.openwrt_board }} !== "")
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: https://github.com/xlighting2017/Actions-Openwrt/releases/download/Immortalwrt_Armvirt/immortalwrt-armvirt-64-default-rootfs.tar.gz
        openwrt_board: ${{ github.event.inputs.openwrt_board }}
        openwrt_kernel: ${{ github.event.inputs.openwrt_kernel }}
        auto_kernel: ${{ github.event.inputs.auto_kernel }}
        openwrt_size: ${{ github.event.inputs.openwrt_size }}
        gh_token: ${{ secrets.GH_TOKEN }}

    - name: Upload OpenWrt Firmware to Release
      id: release
      uses: ncipollo/release-action@main
      if: (!cancelled())
      with:
        tag: OpenWrt_Amlogic_${{ github.event.inputs.openwrt_board }}_${{ env.PACKAGED_OUTPUTDATE }}
        removeArtifacts: false
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        token: ${{ secrets.GH_TOKEN }}
        body: |
            Amlogic/斐讯N1 固件精简版, 打包时间: ${{ env.PACKAGED_OUTPUTDATE }}
            
            Default IP: 192.168.199.253
            Default username: root
            Default password: password
            
            插件列表： 
              ├ amlogic
              ├ ddns
              ├ docker
              ├ filetransfer
              ├ frpc
              ├ OpenClash
              ├ SmartDNS
              ├ ttyd
              ├ KMS 
              └ Zerotier
            
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 7
        keep_minimum_runs: 2
        delete_workflow_pattern: 'Amlogic'

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@master
      if: (!cancelled())
      with:
        repo:
        keep_latest: 3
        delete_tag_pattern: 'Amlogic'
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
