name: Build OpenWRT for N1

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      openwrt_soc:
        description: "Select Amlogic SoC"
        required: false
        default: "s905d"
        type: choice
        options:
          - all
          - s905x3_s905d_s912
          - a311d
          - s922x
          - s922x-n2
          - s922x-reva
          - s905x3
          - s905x2
          - s905x2-km3
          - s912
          - s912-m8s
          - s905d
          - s905d-ki
          - s905x
          - s905w
          - s905
          - s905l3a
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "5.19.1"
        type: choice
        options:
          - 5.4.210_5.10.135_5.15.50
          - 5.4.210_5.10.135
          - 5.10.135_5.15.50
          - 5.15.50_5.19.1
          - 5.4.210
          - 5.10.135
          - 5.15.50
          - 5.19.1
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean
      openwrt_size:
        description: "Set the rootfs size(Unit: MiB)."
        required: false
        default: "960"
    
env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master
  FEEDS_CONF: N1/feeds.conf
  CONFIG_FILE: N1/.config
  DIY_P1_SH: N1/diy-part1.sh
  DIY_P2_SH: N1/diy-part2.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 420 # Add Time
#     if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/JK9Xk)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Load custom feeds
      run: |
        [[ -e "${FEEDS_CONF}" ]] && cp -f ${FEEDS_CONF} openwrt/feeds.conf.default
        chmod +x ${DIY_P1_SH}
        cd openwrt
        ${GITHUB_WORKSPACE}/${DIY_P1_SH}
    
    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [[ -d "files" ]] && mv -f files openwrt/files
        [[ -e "${CONFIG_FILE}" ]] && cp -f ${CONFIG_FILE} openwrt/.config
        chmod +x ${DIY_P2_SH}
        cd openwrt
        ${GITHUB_WORKSPACE}/${DIY_P2_SH}
    
    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    
    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(($(nproc) + 1)) V=s || make -j1 || make -j1 V=s
        echo "::set-output name=status::success"
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT
    
    - name: Package Armvirt as OpenWrt
      if: steps.compile.outputs.status == 'success' && !cancelled()
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: openwrt/bin/targets/*/*/*rootfs.tar.gz
        openwrt_soc: ${{ github.event.inputs.openwrt_soc }}
        openwrt_kernel: ${{ github.event.inputs.openwrt_kernel }}
        auto_kernel: ${{ github.event.inputs.auto_kernel }}
        openwrt_size: ${{ github.event.inputs.openwrt_size }}

    - name: Upload artifact to Actions
      uses: kittaakos/upload-artifact-as-is@master
      if: env.PACKAGED_STATUS == 'success' && !cancelled()
      with:
        path: ${{ env.PACKAGED_OUTPUTPATH }}/

    - name: Upload OpenWrt Firmware to Release
      id: release
      uses: ncipollo/release-action@v1
      if: env.PACKAGED_STATUS == 'success' && !cancelled()
      with:
        name: R${{ env.DATE }} for ${{ env.FILE_NAME }}
        allowUpdates: true
        removeArtifacts: true
        tag: ${{ env.FILE_NAME }}
        commit: main
        token: ${{ secrets.GH_TOKEN }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        body: |
            斐讯N1固件精简版
            ## Openwrt🚀
            Default IP: 192.168.199.253
            Default username: root
            Default password: password
            * N1全新安装方法：
             1. cd root
             2. ./install-to-emmc.sh
            * N1在线升级方法：
             1. cd /mnt/mmcblk2p4
             2. wget 升级脚本链接(包含在Releases内,可直接右键复制链接)
             3. wget img.gz后缀名的固件链接(包含在Releases内,可直接右键复制链接)
             4. gzip -d 解压缩上一步下载的固件全名
             5. chmod +x update-amlogic-openwrt.sh
             6. ./update-amlogic-openwrt.sh 固件名(例：`./update-amlogic-openwrt.sh openwrt_s905d_n1_R21.8.6_k5.14.2-flippy-64+.img`)
             
#    - name: Delete workflow runs
#      uses: GitRML/delete-workflow-runs@main
#      with:
#        token: ${{ secrets.GH_TOKEN }}
#        repository: ${{ github.repository }}
#        retain_days: 60
#        keep_minimum_runs: 60
#
#    - name: Remove old Releases
#      uses: dev-drprasad/delete-older-releases@v0.2.0
#      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
#      with:
#        repo:
#        keep_latest: 30
#        delete_tag_pattern:
#        delete_tags: true
#      env:
#        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
